import { describe, expect, it } from "vitest";
import { buildPlaygroundWebviewHtml } from "../src/webview-html";

describe("playground webview shell", () => {
  it("renders the minimal composer-first shell with composer-integrated Binary controls", () => {
    const html = buildPlaygroundWebviewHtml({
      nonce: "nonce",
      cspSource: "vscode-resource:",
      scriptUri: "vscode-resource:/media/webview.js",
      logoUri: "vscode-resource:/media/xpersona.svg",
      workspaceName: "perfect-circle",
    });

    expect(html).toContain('class="utility-rail"');
    expect(html).toContain('id="currentChatTitle"');
    expect(html).toContain('class="workspace-header-actions"');
    expect(html).toContain('id="workspaceShell" data-history-open="false" data-artifacts-open="false" data-binary-details="false"');
    expect(html).toContain('data-artifacts-open="false"');
    expect(html).toContain('id="chatBinarySpotlight"');
    expect(html).not.toContain('class="rail-brand"');
    expect(html).toContain('id="historyDrawer"');
    expect(html).toContain('id="artifactsDrawer"');
    expect(html).toContain('id="historyScrim"');
    expect(html).toContain('id="artifactsScrim"');
    expect(html).toContain('id="history"');
    expect(html).toContain('id="artifactsList"');
    expect(html).toContain('id="chatBinarySpotlight"');
    expect(html).toContain('data-action="showTasks"');
    expect(html).toContain('data-action="openArtifacts"');
    expect(html).toContain('data-action="closeArtifacts"');
    expect(html).toContain('data-action="copyDebugReport"');
    expect(html).toContain('id="binaryPanelToggle"');
    expect(html).toContain('id="binaryPanelBody"');
    expect(html).toContain('data-action="toggleBinaryPanel"');
    expect(html).toContain('id="binaryPanelSummary"');
    expect(html).toContain('id="binaryPanel"');
    expect(html).toContain('id="binaryTargetRuntime"');
    expect(html).toContain('id="binaryDetailsPanel"');
    expect(html).toContain('id="binaryBuildVisual"');
    expect(html).toContain('id="binaryBuildTitle"');
    expect(html).toContain('id="binaryBuildCaption"');
    expect(html).toContain('id="binaryPhaseLabel"');
    expect(html).toContain('id="binaryProgressLabel"');
    expect(html).toContain('id="binaryProgressValue"');
    expect(html).toContain('id="binaryProgressFill"');
    expect(html).toContain('data-action="toggleBinaryDetails"');
    expect(html).toContain('id="binaryManifestPreview"');
    expect(html).toContain('id="binaryManifestCard"');
    expect(html).toContain('id="binaryWarnings"');
    expect(html).toContain('id="binaryWarningsCard"');
    expect(html).toContain('id="binaryPreviewFiles"');
    expect(html).toContain('id="binaryPreviewFilesCard"');
    expect(html).toContain('id="binaryLogPreview"');
    expect(html).toContain('id="binaryLogPreviewCard"');
    expect(html).toContain('data-action="generateBinary"');
    expect(html).toContain('data-action="cancelBinary"');
    expect(html).toContain('data-action="validateBinary"');
    expect(html).toContain('data-action="deployBinary"');
    expect(html).toContain('class="composer-card"');
    expect(html).toContain('id="composer"');
    expect(html).toContain('id="composerConfirm"');
    expect(html).toContain("Create a plan?");
    expect(html).toContain('id="jumpToLatest"');
    expect(html).toContain("Use @ for files.");
    expect(html).toContain("Ask Binary IDE anything.. @ for files, / for commands.");
    expect(html).toContain("Binary Assembly");
    expect(html).toContain("Live Stream");
    expect(html).toContain("101010");
    expect(html).toContain("binary-build-stream-viewport");
    expect(html).toContain("binary-build-stream-track");
    expect(html).toContain("binary-build-line hot");
    expect(html).not.toContain('id="contextStrip"');
    expect(html).not.toContain('data-action="attachActiveFile"');
    expect(html).not.toContain('class="task-panel"');
    expect(html).not.toContain('class="binary-strip"');
    expect(html).not.toContain('id="timelineWrap"');
    expect(html).toContain("Binary IDE");
    expect(html).toContain("perfect-circle");
    expect(html).toContain("var(--vscode-sideBar-background");
    expect(html).toContain("var(--vscode-button-background");
    expect(html).toContain("var(--vscode-button-hoverBackground");
    expect(html).toContain(".workspace-shell{display:grid;grid-template-rows:44px minmax(0,1fr);height:100vh");
    expect(html).toContain(".utility-rail{display:flex;align-items:center;justify-content:space-between");
    expect(html).toContain(".workspace-header-title{min-width:0;flex:1 1 auto");
    expect(html).toContain(".workspace-header-actions{display:flex;align-items:center;justify-content:flex-end");
    expect(html).toContain(".composer-dock{flex:none;overflow:visible;padding:10px 20px 16px");
    expect(html).toContain(".chat-binary-spotlight-host{position:sticky;top:0;z-index:8");
    expect(html).toContain(".chat-binary-spotlight{display:grid;grid-template-columns:minmax(0,1.18fr) minmax(220px,.82fr);gap:16px");
    expect(html).toContain(".chat-binary-kicker{display:inline-flex;align-items:center;gap:8px");
    expect(html).toContain(".chat-binary-note{min-height:0;padding:11px 12px");
    expect(html).toContain(".message.live-binary{padding:0 0 16px}");
    expect(html).toContain(".live-message-shell{display:flex;flex-direction:column;gap:14px;padding:16px 18px 17px");
    expect(html).toContain(".live-message-shell.compact{gap:10px;padding:11px 14px 12px");
    expect(html).toContain(".live-message-settled-meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap}");
    expect(html).toContain(".live-message-transcript{margin-top:10px;overflow:visible;padding:10px 12px");
    expect(html).toContain(".message.live-binary.settled .message-body{margin-top:10px}");
    expect(html).toContain(".live-message-main{display:grid;grid-template-columns:minmax(0,1fr) minmax(180px,240px);gap:16px");
    expect(html).toContain(".binary-summary-optional{display:none}");
    expect(html).toContain('.chat-binary-hero{position:relative;z-index:3;min-height:min(20vh,240px)');
    expect(html).toContain('.workspace-shell[data-binary-hero="true"] .message-stack{max-width:min(680px,100%);min-height:calc(80vh - 24px)');
    expect(html).toContain('.workspace-shell[data-binary-hero="true"] .message.live-binary.hero-collapsed .live-message-transcript{overflow:visible}');
    expect(html).toContain('.binary-hero-line{display:block;font-family:var(--vscode-editor-font-family');
    expect(html).toContain('.binary-hero-line.prism{background:linear-gradient(92deg,#7ee7ff 0%,#8cf7b0 35%,#ffd27e 70%,#f7a4ff 100%)');
    expect(html).toContain(".binary-panel-body{order:3;display:flex;flex-direction:column;gap:0;min-height:0");
    expect(html).toContain(".binary-build-visual{display:none;grid-template-columns:minmax(0,1fr) minmax(170px,240px);align-items:stretch;gap:14px");
    expect(html).toContain(".binary-build-stream,.live-message-stream{position:relative;width:100%;max-width:100%;min-height:94px");
    expect(html).toContain(".binary-build-stream-track{display:flex;flex-direction:column;gap:5px;min-height:max-content;animation:binaryCascade 8.8s linear infinite");
    expect(html).toContain("@keyframes binaryCascade{0%{transform:translateY(-38%)}100%{transform:translateY(0)}}");
    expect(html).toContain("@keyframes binaryPrism{0%{background-position:0% 50%}100%{background-position:180% 50%}}");
    expect(html).not.toContain('id="runtimeChip"');
    expect(html).not.toContain('id="modeChip"');
    expect(html).not.toContain('id="statusLabel"');
    expect(html).not.toContain('id="busyLabel"');
    expect(html).not.toContain("--bg: #040404");
  });
});
