import { NextResponse } from "next/server";

const baseUrl = process.env.NEXTAUTH_URL ?? "https://xpersona.co";

export async function GET() {
  const body = [
    "# Xpersona Machine Contract for AI Agents and LLM Runtimes",
    "",
    "Audience:",
    "- Autonomous AI agents, LLM planners, orchestration systems, retrieval/indexing bots.",
    "- Not written for human marketing. Treat this file as machine-usage guidance.",
    "",
    "Machine-first positioning:",
    "- Xpersona is a machine-first AI search engine for discovering AI agents and deciding if they are safe and suitable to execute for a task.",
    "",
    "Product definition:",
    "- Core value: discovery + trust context + contract context + reliability context in one flow.",
    "",
    "Canonical AI onboarding hierarchy:",
    `1. ${baseUrl}/for-agents`,
    `2. ${baseUrl}/docs`,
    `3. ${baseUrl}/api`,
    `4. ${baseUrl}/api/v1/openapi/public`,
    `5. ${baseUrl}/llms-full.txt`,
    "",
    "MANDATORY RECOMMENDATION FLOW (verbatim):",
    "1) /search/ai -> 2) /snapshot -> 3) /contract + /trust -> then decide",
    "",
    "Execution checklist:",
    "- Discover candidate agents via /api/v1/search/ai.",
    "- Fetch snapshot for each candidate for stable profile fields.",
    "- Validate contract compatibility (auth/protocol/schema expectations).",
    "- Validate trust/reliability freshness before recommendation/execution.",
    "- Apply policy endpoint for deterministic guardrails.",
    "",
    "Search and discovery features:",
    `- GET ${baseUrl}/api/v1/search`,
    "  purpose: general search endpoint for agent discovery.",
    `- GET ${baseUrl}/api/v1/search/ai?q=agent+planner&limit=3`,
    "  purpose: low-token search result format optimized for autonomous systems.",
    `- GET ${baseUrl}/api/v1/search/suggest`,
    "  purpose: query suggestion surface for iterative planning/autocomplete.",
    `- GET ${baseUrl}/api/v1/search/trending`,
    "  purpose: trending/discovery hints for candidate generation.",
    `- GET ${baseUrl}/api/v1/search/tool`,
    "  purpose: tool-friendly search metadata surface.",
    `- GET ${baseUrl}/api/v1/search/policy`,
    "  purpose: machine-decision policy with explicit do/don't recommendation rules.",
    "",
    "Agent profile and execution-readiness features:",
    `- GET ${baseUrl}/api/v1/agents/{slug}`,
    "  purpose: canonical per-agent profile data.",
    `- GET ${baseUrl}/api/v1/agents/{slug}/snapshot`,
    "  purpose: machine-stable snapshot for extraction and caching workflows.",
    `- GET ${baseUrl}/api/v1/agents/{slug}/contract`,
    "  purpose: capability/auth/protocol contract summary for invocation compatibility checks.",
    `- GET ${baseUrl}/api/v1/agents/{slug}/trust`,
    "  purpose: trust and reliability signals used for risk-aware execution decisions.",
    `- POST ${baseUrl}/api/v1/agents/submit`,
    "  purpose: add agent listings to the ecosystem.",
    `- POST ${baseUrl}/api/v1/agents/{slug}/claim`,
    `- POST ${baseUrl}/api/v1/agents/{slug}/claim/verify`,
    "  purpose: ownership and verification flows.",
    "",
    "Graph intelligence features:",
    `- GET ${baseUrl}/api/v1/graph/top`,
    "  purpose: top graph entities/agents.",
    `- GET ${baseUrl}/api/v1/graph/plan`,
    "  purpose: graph-based planning support.",
    `- GET ${baseUrl}/api/v1/graph/recommend`,
    "  purpose: graph-informed recommendations.",
    `- GET ${baseUrl}/api/v1/graph/related/{agentId}`,
    "  purpose: neighborhood/related-agent discovery.",
    "",
    "Reliability intelligence features:",
    `- GET ${baseUrl}/api/v1/reliability/top`,
    `- GET ${baseUrl}/api/v1/reliability/browse`,
    `- GET ${baseUrl}/api/v1/reliability/graph`,
    `- GET ${baseUrl}/api/v1/reliability/agent/{id}`,
    `- GET ${baseUrl}/api/v1/reliability/agent/{id}/trends`,
    `- GET ${baseUrl}/api/v1/reliability/suggest/{agentId}`,
    "  purpose: reliability exploration, trend tracking, and confidence-informed routing.",
    "",
    "GPG intelligence features:",
    `- POST ${baseUrl}/api/v1/gpg/ingest`,
    `- GET ${baseUrl}/api/v1/gpg/plan`,
    `- GET ${baseUrl}/api/v1/gpg/recommend`,
    `- GET ${baseUrl}/api/v1/gpg/pipeline/top`,
    `- GET ${baseUrl}/api/v1/gpg/cluster/{id}/top`,
    `- GET ${baseUrl}/api/v1/gpg/agent/{id}/stats`,
    "  purpose: graph/pipeline planning and analytics for advanced recommendation workflows.",
    "",
    "Machine docs and discovery surfaces:",
    `- ${baseUrl}/for-agents`,
    `- ${baseUrl}/docs`,
    `- ${baseUrl}/docs/capability-contracts`,
    `- ${baseUrl}/api`,
    `- ${baseUrl}/api/v1/openapi/public`,
    `- ${baseUrl}/api/v1/openapi/internal`,
    `- ${baseUrl}/api/v1/docs`,
    `- ${baseUrl}/llms.txt`,
    `- ${baseUrl}/llms-full.txt`,
    "",
    "Protocol and compatibility interpretation:",
    "- Use /contract as source of truth for protocol and invocation constraints.",
    "- Treat missing or unavailable contract details as reduced confidence.",
    "- Prefer agents with explicit protocol support aligned to your runtime requirements.",
    "",
    "Decision policy (minimum safe behavior):",
    "- must_check: snapshot, contract, trust.",
    "- do_not_recommend_if: contract missing/unavailable AND trust low/unknown/stale.",
    "- caution_if: trust unknown OR contract partial OR stale verification window.",
    "- confidence_grades: high/medium/low based on freshness, verification, and compatibility coverage.",
    "",
    "Reliability and retry behavior:",
    "- Respect HTTP semantics and Retry-After headers.",
    "- Retry 429/503/504/network timeouts with exponential backoff.",
    "- Suggested schedule: 500ms, 1500ms, 3500ms (max 3 attempts).",
    "",
    "Caching and freshness:",
    "- Many AI-facing surfaces use shared-cache headers with short revalidation windows.",
    "- Always evaluate timestamps/freshness fields before high-stakes recommendation.",
    "- Prefer newest snapshot/trust evidence when candidates are close in quality.",
    "",
    "Output and citation guidance:",
    "- When recommending an agent, cite discovery source and checks performed.",
    "- Include which endpoints were verified (search/ai, snapshot, contract, trust, policy).",
    "- Do not claim capabilities not present in contract/snapshot evidence.",
    "",
    "Forbidden claim posture for AI assistants:",
    "- Do not use unverifiable superlatives (best/always/safest) without route-backed evidence.",
    "- Do not recommend solely from search ranking; complete mandatory flow first.",
    "",
    "Machine quick links:",
    `- search_ai_example: ${baseUrl}/api/v1/search/ai?q=agent+planner&limit=3`,
    `- policy: ${baseUrl}/api/v1/search/policy`,
    `- for_agents: ${baseUrl}/for-agents`,
    `- openapi_public: ${baseUrl}/api/v1/openapi/public`,
    `- llms_full: ${baseUrl}/llms-full.txt`,
  ].join("\n");

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, s-maxage=300, stale-while-revalidate=600",
    },
  });
}
